//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Provetex
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int C_id_user { get; set; }
        public string C_nom { get; set; }
        public string C_user_name { get; set; }
        public string C_password { get; set; }
        public string C_question { get; set; }
        public string C_repence { get; set; }
        public System.DateTime C_favorite_date { get; set; }
    }
}
